name: 'Download a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
outputs:
  download-path:
    description: 'Path of artifact download'
runs:
  using: 'node16'
  main: 'dist/index.js'
- name: Upload artifact for deployment job
  uses: actions/upload-artifact@v2.3.1
  with:
    name: webapp
    path: website/**
    if-no-files-found: warn
